name: dementia
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  http: ^0.13.6
  fpdart: ^0.6.0
  internet_connection_checker_plus: ^1.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  bloc: ^8.1.3
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  collection: ^1.17.0
  lottie: ^2.3.2
  go_router: ^12.1.1
  talker_flutter: ^3.6.0
  flutter_hooks: 0.18.6
  intl: ^0.18.1
  url_launcher: ^6.1.11
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.3.3
  go_router_builder: ^2.3.4
  bloc_test: ^9.1.6
  golden_toolkit: ^0.15.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/logo/

  fonts:
    - family: MarkPro
      fonts:
        - asset: fonts/FontFont_FF.Mark.Pro.otf
        - asset: fonts/FontFont_FF.Mark.Pro.Bold.otf
          weight: 700
